[build]
  command = "npm run build"
  publish = ".next" # Le plugin se charge de tout, on laisse sur .next

# Indique à Netlify d'utiliser le plugin pour Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"