
[build]
  command = "npm run build"
  publish = "out"

[functions]
  directory = "netlify/functions"

# Redirection essentielle pour le routing SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
