[build]
  command = "npm run build"
  publish = ".next/standalone" # Le dossier créé par 'output: standalone'

# Configuration nécessaire pour le bon fonctionnement de Next.js sur Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Utilisez le plugin officiel Netlify pour Next.js pour une optimisation maximale
[[plugins]]
  package = "@netlify/plugin-nextjs"