[build]
  command = "npm run build"
  publish = ".next/standalone/.next"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/_next/static/*"
  to = "/static/*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/server.js"
  status = 200
  force = true
