[build]
  command = "npm run build"
  publish = "out" # Next.js place les fichiers static dans '/out' avec output: 'export'

# Redirection pour SPA - essentiel pour le routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200