[build]
  command = "npm run build"
  publish = ".next/standalone"

[functions]
  directory = ".next/standalone/.next/server/pages"
  included_files = [".next/standalone/.next/server/**"]

[[redirects]]
  from = "/_next/static/*"
  to = "/.next/static/*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { "path" = "!^/api/.*" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
